spring.application.name=project-two

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_management
spring.datasource.username=postgres
spring.datasource.password=password

#hibernate 
# in production write validate / none , in dev we can have update
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

#actuator
management.endpoints.web.exposure.include=health, metrics, info, beans, loggers, env
management.endpoint.health.show-details=always

#sqs

# spring.cloud.aws.region.static:eu-north-1

aws.sqs.queue-url:https://sqs.eu-north-1.amazonaws.com/631525177649/MyTestQueue

#sqs-receiver
spring.cloud.aws.sqs.listener.max-concurrent-messages=10
spring.cloud.aws.sqs.listener.max-messages-per-poll=5
spring.cloud.aws.sqs.listener.poll-timeout=20s

# Resilience4j Retry config for SQS producer
resilience4j.retry.instances.sqsProducer.max-attempts=3
resilience4j.retry.instances.sqsProducer.wait-duration=1s
resilience4j.retry.instances.sqsProducer.enable-exponential-backoff=true
resilience4j.retry.instances.sqsProducer.exponential-backoff-multiplier=2
resilience4j.retry.instances.sqsProducer.retry-exceptions=com.moon.project_two.SQSProducer.RetryableException
resilience4j.retry.instances.sqsProducer.ignore-exceptions=com.moon.project_two.SQSProducer.NonRetryableException